server:
  tomcat:
    max-swallow-size: 20MB      # Tomcat最大请求体大小
    connection-timeout: 60000   # 连接超时
  port: 8082 # 项目启动的端口F

spring:
  servlet:
    multipart:
      max-file-size: 10MB        # 单个文件最大大小
      max-request-size: 20MB     # 整个请求最大大小
  profiles:
    active: dev # 默认激活 dev 本地开发环境

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml



