server:
  tomcat:
    max-swallow-size: 20MB
    connection-timeout: 60000
  port: 8081 # 项目启动的端口

spring:
  servlet:
    multipart:
      max-file-size: 10MB        # 单个文件最大大小
      max-request-size: 20MB     # 整个请求最大大小
  profiles:
    active: dev # 默认激活 dev 本地开发环境

storage:
  type: minio # 对象存储类型
