storage:
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: test
    secretKey: test123456
  aliyun-oss:
    # OSS 服务的访问域名，请根据实际使用的 OSS 区域替换为对应的 endpoint
    endpoint: xxx
    # 阿里云账号的 AccessKey ID，用于身份验证
    accessKey: xxx
    # 阿里云账号的 AccessKey Secret，用于身份验证
    secretKey: xxx
