server:
  port: 8092 # 项目启动的端口

elasticsearch:
  address: 127.0.0.1:9200 # Elasticsearch 地址
  hotUpdateExtDict: E:\linux\docker\elasticsearch\config\analysis-ik\custom\mydict_hot_update.dic


spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml


canal: # Canal 配置
  address: 127.0.0.1:11111 # 链接地址
  destination: example # 数据目标
  username: canal # 数据库用户名
  password: canal # 数据库密码
  subscribe: oursphere.t_note,oursphere.t_user # 订阅规则，只订阅笔记表和用户表
  batchSize: 1000 # 一批次拉取数据量
